version 0.1.6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,18 @@
 #!/bin/sh
 set -x
+
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
+export CC
+export CFLAGS
+export CPPFLAGS
+
 (cd src/scrypt-1.1.6/ && chmod +x ./configure)
 (cd src/scrypt-1.1.6/ && ./configure)
